In [1]:
import numpy as np
import pandas as pd 

data = {
    "name": ["Ram", "Sita", "Hari", "Gita", "John", "asma", "bibek", "sabal"],
    "age": [22, 25, 28, 21, 30, 20, 31, 23],
    "salary": [30000, 45000, 50000, 28000, 60000, 45000, 40000, 50000],
    "city": ['kathmandu', 'pokhara', 'kathmandu', 'dhangadi', 'chitwan', 'dhading', 'pokhara', 'jhapa']
}

data_df = pd.DataFrame(data)

# top row


data_df.head()

   name  age  salary       city
0   Ram   22   30000  kathmandu
1  Sita   25   45000    pokhara
2  Hari   28   50000  kathmandu
3  Gita   21   28000   dhangadi
4  John   30   60000    chitwan

In [2]:
data_df.tail()

    name  age  salary      city
3   Gita   21   28000  dhangadi
4   John   30   60000   chitwan
5   asma   20   45000   dhading
6  bibek   31   40000   pokhara
7  sabal   23   50000     jhapa

In [3]:
data_df.describe()

             age        salary
count   8.000000      8.000000
mean   25.000000  43500.000000
std     4.208834  10663.690061
min    20.000000  28000.000000
25%    21.750000  37500.000000
50%    24.000000  45000.000000
75%    28.500000  50000.000000
max    31.000000  60000.000000

In [6]:
print(data_df["age"]).mean()

#print(data_df["salary"]).mean()

0    22
1    25
2    28
3    21
4    30
5    20
6    31
7    23
Name: age, dtype: int64

AttributeError: 'NoneType' object has no attribute 'mean'

In [7]:
age_data=data_df["age"]
age_data

0    22
1    25
2    28
3    21
4    30
5    20
6    31
7    23
Name: age, dtype: int64

In [8]:
type(age_data)

pandas.Series

In [9]:
new_df=data_df[["name","age","salary"]]
print(new_df)

    name  age  salary
0    Ram   22   30000
1   Sita   25   45000
2   Hari   28   50000
3   Gita   21   28000
4   John   30   60000
5   asma   20   45000
6  bibek   31   40000
7  sabal   23   50000

In [10]:
#selecting rows
#using iloc-> integer location
data_df.iloc[0]

name            Ram
age              22
salary        30000
city      kathmandu
Name: 0, dtype: object

In [11]:
#first three rows
data_df.iloc[0:3]

   name  age  salary       city
0   Ram   22   30000  kathmandu
1  Sita   25   45000    pokhara
2  Hari   28   50000  kathmandu

In [12]:
#specific rows and columns
data_df.iloc[0,1]

np.int64(22)

In [13]:
data_df.iloc[0]

name            Ram
age              22
salary        30000
city      kathmandu
Name: 0, dtype: object

In [14]:
data_df.loc[0,["name","age"]]

name    Ram
age      22
Name: 0, dtype: object

In [15]:
#Multiple rows
data_df.loc[0:2,["name","salary"]]

   name  salary
0   Ram   30000
1  Sita   45000
2  Hari   50000

In [ ]:
#iloc lae index use garxa and loc lae value ko name

Filtering Data

In [16]:
#age greater than condition

data_df[data_df["age"]>25]

    name  age  salary       city
2   Hari   28   50000  kathmandu
4   John   30   60000    chitwan
6  bibek   31   40000    pokhara

In [18]:
#age greater than 22 and salary greater than 40,000
data_df[(data_df["age"] > 22) & (data_df["salary"] > 40000)]

    name  age  salary       city
1   Sita   25   45000    pokhara
2   Hari   28   50000  kathmandu
4   John   30   60000    chitwan
7  sabal   23   50000      jhapa

Reading CSV file

In [20]:
#filepath="D:\MovedFolder\DataSciencePythonevening\DataScienceCourse\numpy\dataset\index_1.csv"
filepath=filepath = r"D:\MovedFolder\DataSciencePythonevening\DataScienceCourse\numpy\dataset\index_1.csv"
sales_df=pd.read_csv(filepath)
sales_df.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [21]:
sales_df.describe()

             money
count  3636.000000
mean     31.746859
std       4.919926
min      18.120000
25%      27.920000
50%      32.820000
75%      35.760000
max      40.000000

In [22]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   str
 1   datetime     3636 non-null   str
 2   cash_type    3636 non-null   str
 3   card         3547 non-null   str
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   str
dtypes: float64(1), str(5)
memory usage: 170.6 KB

In [23]:
sales_df.isnull()

       date  datetime  cash_type   card  money  coffee_name
0     False     False      False  False  False        False
1     False     False      False  False  False        False
2     False     False      False  False  False        False
3     False     False      False  False  False        False
4     False     False      False  False  False        False
...     ...       ...        ...    ...    ...          ...
3631  False     False      False  False  False        False
3632  False     False      False  False  False        False
3633  False     False      False  False  False        False
3634  False     False      False  False  False        False
3635  False     False      False  False  False        False

[3636 rows x 6 columns]

In [ ]:
# import pandas as pd

# data = {    "name": [        "Ram", "Sita", "Hari",        "Gita", "John", "Rita"    ],    "age": [20, 24, 22, 27, 30, 25],    "city": [        "Kathmandu", "Pokhara", "Kathmandu",        "Chitwan", "Pokhara", "Kathmandu"    ],    "marks": [75, 88, 65, 92, 55, 81]}

# df = pd.DataFrame(data)

Display the complete DataFrame.
Display the first 3 rows.
Find the number of rows and columns.
Display all column names.
Select only the name column.
Select name and marks.
Find the average marks.
Find the highest and lowest marks.
Find students older than 23.
Find students with marks greater than 80.
Find students from Kathmandu.
Find students from Kathmandu whose marks are greater than 75.
Display the first student's data using iloc.
Select rows 1–3 using iloc.
Use describe() to inspect numerical columns.

In [24]:
import pandas as pd

data = { "name": [ "Ram", "Sita", "Hari",        "Gita", "John", "Rita"    ],    "age": [20, 24, 22, 27, 30, 25],    "city": [        "Kathmandu", "Pokhara", "Kathmandu",        "Chitwan", "Pokhara", "Kathmandu"    ],    "marks": [75, 88, 65, 92, 55, 81]}

df = pd.DataFrame(data)

In [25]:
print(df)

   name  age       city  marks
0   Ram   20  Kathmandu     75
1  Sita   24    Pokhara     88
2  Hari   22  Kathmandu     65
3  Gita   27    Chitwan     92
4  John   30    Pokhara     55
5  Rita   25  Kathmandu     81

In [26]:
df.head(3)

   name  age       city  marks
0   Ram   20  Kathmandu     75
1  Sita   24    Pokhara     88
2  Hari   22  Kathmandu     65

In [30]:
df.shape

(6, 4)

In [32]:
df.columns

Index(['name', 'age', 'city', 'marks'], dtype='str')

In [33]:
df["name"]

0     Ram
1    Sita
2    Hari
3    Gita
4    John
5    Rita
Name: name, dtype: str

In [40]:
df.loc[:,["name","marks"]]

#df.loc[:, ["name", "marks"]]

   name  marks
0   Ram     75
1  Sita     88
2  Hari     65
3  Gita     92
4  John     55
5  Rita     81

In [49]:
print("The average marks is:",df["marks"].mean())

The average marks is: 76.0

np.int64(92)

np.int64(55)

In [47]:
print("The highest marks is:", df["marks"].max())

The highest marks is: 92

In [48]:
print("The lowest marks is:",df["marks"].min())

The lowest marks is: 55

In [50]:
df[df["age"]>23]

   name  age       city  marks
1  Sita   24    Pokhara     88
3  Gita   27    Chitwan     92
4  John   30    Pokhara     55
5  Rita   25  Kathmandu     81

In [51]:
df[df["marks"]>80]

   name  age       city  marks
1  Sita   24    Pokhara     88
3  Gita   27    Chitwan     92
5  Rita   25  Kathmandu     81

In [52]:
df[df["city"]=="Kathmandu"]

   name  age       city  marks
0   Ram   20  Kathmandu     75
2  Hari   22  Kathmandu     65
5  Rita   25  Kathmandu     81

In [54]:
df[(df["city"] == "Kathmandu") & (df["marks"] > 75)]

   name  age       city  marks
5  Rita   25  Kathmandu     81

Display the first student's data using iloc.
Select rows 1–3 using iloc.
Use describe() to inspect numerical columns.

In [55]:
df.iloc[0]

name           Ram
age             20
city     Kathmandu
marks           75
Name: 0, dtype: object

In [59]:
df.iloc[1:4]

   name  age       city  marks
1  Sita   24    Pokhara     88
2  Hari   22  Kathmandu     65
3  Gita   27    Chitwan     92

In [57]:
df.describe()

             age      marks
count   6.000000   6.000000
mean   24.666667  76.000000
std     3.559026  14.057027
min    20.000000  55.000000
25%    22.500000  67.500000
50%    24.500000  78.000000
75%    26.500000  86.250000
max    30.000000  92.000000

In [58]:
df

   name  age       city  marks
0   Ram   20  Kathmandu     75
1  Sita   24    Pokhara     88
2  Hari   22  Kathmandu     65
3  Gita   27    Chitwan     92
4  John   30    Pokhara     55
5  Rita   25  Kathmandu     81