Day2 Pandas

In [1]:
import numpy as np
import pandas as pd

In [83]:
employee_data = {
    "name": [
        "  Ram Sharma",
        "sita Thapa ",
        "Hari KC",
        "Gita Rai",
        "Ram sharma",
        "Nabin Gurung"
    ],
    "age": [25, 28, np.nan, 30, 25, 27],
    "city": [
        "Kathmandu",
        "Pokhara",
        "Kathmandu",
        None,
        "Kathmandu",
        "Chitwan"
    ],
    "salary": ["50000", "65000", "55000", "70000", "50000", "60000"],
    "department": ["IT", "HR", "IT", "Finance", "IT", "HR"]
}

employee_df=pd.DataFrame(employee_data)
employee_df.head()

           name   age       city salary department
0    Ram Sharma  25.0  Kathmandu  50000         IT
1   sita Thapa   28.0    Pokhara  65000         HR
2       Hari KC   NaN  Kathmandu  55000         IT
3      Gita Rai  30.0        NaN  70000    Finance
4    Ram sharma  25.0  Kathmandu  50000         IT

In [132]:
employee_df["age"]=employee_df["age"].fillna(employee_df["age"].mean()).astype(int)
employee_df.head()

           name  age     city  salary department salary_level  department_code
1   sita Thapa    28  Pokhara   65000         HR         High                2
3      Gita Rai   30      NaN   70000    Finance         High                3
5  Nabin Gurung   27  Chitwan   60000         HR         High                2

In [3]:
employee_df.dtypes

name              str
age           float64
city              str
salary            str
department        str
dtype: object

In [5]:
employee_df.isnull().sum()

name          0
age           1
city          1
salary        0
department    0
dtype: int64

In [131]:
#fill missing value
employee_df["age"]=employee_df["age"].fillna(employee_df["age"].mean())
employee_df.head(5)

,name,age,city,salary,department,salary_level,department_code
1,sita Thapa,28.0,Pokhara,65000,HR,High,2
3,Gita Rai,30.0,NaN,70000,Finance,High,3
5,Nabin Gurung,27.0,Chitwan,60000,HR,High,2

In [54]:
#to fill string fill it with mode.
employee_df["city"]=employee_df["city"].fillna(employee_df["city"].mode()[0])
print(employee_df)

           name   age       city   salary  department
0    Ram Sharma  25.0  Kathmandu  50000.0  Technology
1    Sita Thapa  28.0    Pokhara  65000.0          HR
2       Hari Kc   NaN  Kathmandu  55000.0  Technology
3      Gita Rai  30.0  Kathmandu  70000.0     Finance
5  Nabin Gurung  27.0    Chitwan  60000.0          HR

In [28]:
employee_df["city"]=employee_df["city"].fillna("Pokhara")
employee_df

           name   age       city salary department
0    Ram Sharma  25.0  Kathmandu  50000         IT
1   Sita Thapa   28.0    Pokhara  65000         HR
2       Hari KC  27.0  Kathmandu  55000         IT
3      Gita Rai  30.0  Kathmandu  70000    Finance
4    Ram Sharma  25.0  Kathmandu  50000         IT
5  Nabin Gurung  27.0    Chitwan  60000         HR

In [12]:
employee_df.isnull().sum()

name          0
age           0
city          0
salary        0
department    0
dtype: int64

In [8]:
new_df=employee_df.copy()
new_df.dropna(subset=["age"])

           name   age       city salary department
0    Ram Sharma  25.0  Kathmandu  50000         IT
1   Sita Thapa   28.0    Pokhara  65000         HR
3      Gita Rai  30.0        NaN  70000    Finance
4    Ram Sharma  25.0  Kathmandu  50000         IT
5  Nabin Gurung  27.0    Chitwan  60000         HR

In [37]:
#Clean Name
employee_df["name"]=employee_df["name"].str.strip()
employee_df

           name   age       city salary department
0    Ram Sharma  25.0  Kathmandu  50000         IT
1    Sita Thapa  28.0    Pokhara  65000         HR
2       Hari Kc   NaN  Kathmandu  55000         IT
3      Gita Rai  30.0        NaN  70000    Finance
4    Ram Sharma  25.0  Kathmandu  50000         IT
5  Nabin Gurung  27.0    Chitwan  60000         HR

In [39]:
employee_df["name"]=employee_df["name"].str.lower()
employee_df

           name   age       city salary department
0    ram sharma  25.0  Kathmandu  50000         IT
1    sita thapa  28.0    Pokhara  65000         HR
2       hari kc   NaN  Kathmandu  55000         IT
3      gita rai  30.0        NaN  70000    Finance
4    ram sharma  25.0  Kathmandu  50000         IT
5  nabin gurung  27.0    Chitwan  60000         HR

In [40]:
employee_df["name"]=employee_df["name"].str.title()
employee_df

           name   age       city salary department
0    Ram Sharma  25.0  Kathmandu  50000         IT
1    Sita Thapa  28.0    Pokhara  65000         HR
2       Hari Kc   NaN  Kathmandu  55000         IT
3      Gita Rai  30.0        NaN  70000    Finance
4    Ram Sharma  25.0  Kathmandu  50000         IT
5  Nabin Gurung  27.0    Chitwan  60000         HR

In [41]:
#replace specific value from columns(IT- Technology)
employee_df["department"]=employee_df["department"].replace("IT","Technology")
employee_df.head(10)

           name   age       city salary  department
0    Ram Sharma  25.0  Kathmandu  50000  Technology
1    Sita Thapa  28.0    Pokhara  65000          HR
2       Hari Kc   NaN  Kathmandu  55000  Technology
3      Gita Rai  30.0        NaN  70000     Finance
4    Ram Sharma  25.0  Kathmandu  50000  Technology
5  Nabin Gurung  27.0    Chitwan  60000          HR

In [42]:
employee_df.describe

<bound method NDFrame.describe of            name   age       city salary  department
0    Ram Sharma  25.0  Kathmandu  50000  Technology
1    Sita Thapa  28.0    Pokhara  65000          HR
2       Hari Kc   NaN  Kathmandu  55000  Technology
3      Gita Rai  30.0        NaN  70000     Finance
4    Ram Sharma  25.0  Kathmandu  50000  Technology
5  Nabin Gurung  27.0    Chitwan  60000          HR>

In [43]:
employee_df["salary"]=employee_df["salary"].astype("float")
employee_df.head()

         name   age       city   salary  department
0  Ram Sharma  25.0  Kathmandu  50000.0  Technology
1  Sita Thapa  28.0    Pokhara  65000.0          HR
2     Hari Kc   NaN  Kathmandu  55000.0  Technology
3    Gita Rai  30.0        NaN  70000.0     Finance
4  Ram Sharma  25.0  Kathmandu  50000.0  Technology

In [44]:
employee_df.dtypes

name              str
age           float64
city              str
salary        float64
department        str
dtype: object

In [133]:
employee_df["age"]=employee_df["age"].astype("int")
employee_df.head()

           name  age     city  salary department salary_level  department_code
1   sita Thapa    28  Pokhara   65000         HR         High                2
3      Gita Rai   30      NaN   70000    Finance         High                3
5  Nabin Gurung   27  Chitwan   60000         HR         High                2

In [48]:
#Duplicate value

employee_df.duplicated().sum()

np.int64(1)

In [49]:
employee_df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [50]:
#view duplicate
employee_df[employee_df.duplicated()]

         name   age       city   salary  department
4  Ram Sharma  25.0  Kathmandu  50000.0  Technology

In [55]:
employee_df=employee_df.drop_duplicates()
employee_df.head()

           name   age       city   salary  department
0    Ram Sharma  25.0  Kathmandu  50000.0  Technology
1    Sita Thapa  28.0    Pokhara  65000.0          HR
2       Hari Kc   NaN  Kathmandu  55000.0  Technology
3      Gita Rai  30.0  Kathmandu  70000.0     Finance
5  Nabin Gurung  27.0    Chitwan  60000.0          HR

In [56]:
#on specific column
employee_df.duplicated(subset=["name"]).sum()

np.int64(0)

In [60]:
employee_data = {
    "name": [
        "  Ram Sharma",
        "sita Thapa ",
        "Hari KC",
        "Gita Rai",
        "Ram sharma",
        "Nabin GurunG"
    ],
    "age": [25, 28, np.nan, 30, 25, 27],
    "city": [
        "Kathmandu",
        "Pokhara",
        "Kathmandu",
        None,
        "Kathmandu",
        "Chitwan"
    ],
    "email": [
        'employee482@gmail.com',
        'employee731@gmail.com',
        'employee156@gmail.com',
        'employee904@gmail.com',
        'employee327@gmail.com',
        'employee618@gmail.com'
        ],
    "salary": ["50000", "65000", "55000", "70000", "50000", "60000"],
    "department": ["IT", "HR", "IT", "Finance", "IT", "HR"]
}

new_empdf=pd.DataFrame(employee_df)
new_empdf.head(10)

           name   age       city   salary  department
0    Ram Sharma  25.0  Kathmandu  50000.0  Technology
1    Sita Thapa  28.0    Pokhara  65000.0          HR
2       Hari Kc   NaN  Kathmandu  55000.0  Technology
3      Gita Rai  30.0  Kathmandu  70000.0     Finance
5  Nabin Gurung  27.0    Chitwan  60000.0          HR

In [ ]:
#Rename columns
employee_df=employee_df.rename(columns={"name":"Employee_name", "salary":"Monthly_salary"})
employee_df.head(10)

# employee_df = employee_df.rename(columns={
#     "name": "Employee_name",
#     "salary": "Monthly_salary"
# })

# employee_df.head(10)

           name   age       city   salary  department
0    Ram Sharma  25.0  Kathmandu  50000.0  Technology
1    Sita Thapa  28.0    Pokhara  65000.0          HR
2       Hari Kc   NaN  Kathmandu  55000.0  Technology
3      Gita Rai  30.0  Kathmandu  70000.0     Finance
5  Nabin Gurung  27.0    Chitwan  60000.0          HR

In [65]:
employee_df.drop(columns=["city"])

           name   age   salary  department
0    Ram Sharma  25.0  50000.0  Technology
1    Sita Thapa  28.0  65000.0          HR
2       Hari Kc   NaN  55000.0  Technology
3      Gita Rai  30.0  70000.0     Finance
5  Nabin Gurung  27.0  60000.0          HR

In [67]:
#add new columns
employee_df["annual_salary"]=employee_df["salary"]*12
employee_df.head()

           name   age       city   salary  department  annual_salary
0    Ram Sharma  25.0  Kathmandu  50000.0  Technology       600000.0
1    Sita Thapa  28.0    Pokhara  65000.0          HR       780000.0
2       Hari Kc   NaN  Kathmandu  55000.0  Technology       660000.0
3      Gita Rai  30.0  Kathmandu  70000.0     Finance       840000.0
5  Nabin Gurung  27.0    Chitwan  60000.0          HR       720000.0

In [ ]:
#add bonus(10%) and compensation(salary+bonus)
employee_df["bonus"]=employee_df["salary"] * 0.1
employee_df.head()

           name   age       city   salary  department  annual_salary   bonus
0    Ram Sharma  25.0  Kathmandu  50000.0  Technology       600000.0  5000.0
1    Sita Thapa  28.0    Pokhara  65000.0          HR       780000.0  6500.0
2       Hari Kc   NaN  Kathmandu  55000.0  Technology       660000.0  5500.0
3      Gita Rai  30.0  Kathmandu  70000.0     Finance       840000.0  7000.0
5  Nabin Gurung  27.0    Chitwan  60000.0          HR       720000.0  6000.0

In [71]:
employee_df["compensation"]=employee_df["salary"].add(employee_df["bonus"])
employee_df.head()

,name,age,city,salary,department,annual_salary,bonus,compensation
0,Ram Sharma,25.0,Kathmandu,50000.0,Technology,600000.0,5000.0,55000.0
1,Sita Thapa,28.0,Pokhara,65000.0,HR,780000.0,6500.0,71500.0
2,Hari Kc,NaN,Kathmandu,55000.0,Technology,660000.0,5500.0,60500.0
3,Gita Rai,30.0,Kathmandu,70000.0,Finance,840000.0,7000.0,77000.0
5,Nabin Gurung,27.0,Chitwan,60000.0,HR,720000.0,6000.0,66000.0

In [112]:
employee_df["salary"].astype("float")

0    50000.0
1    65000.0
2    55000.0
3    70000.0
4    50000.0
5    60000.0
Name: salary, dtype: float64

apply()

In [113]:
employee_df["salary"] = pd.to_numeric(employee_df["salary"])

In [72]:
def salary_level(salary):
    if salary>65000:
        return "High"
    elif salary >50000:
        return"Medium" 
    else:
        return "Low"

In [74]:
employee_df["salary_level"]=employee_df["salary"].apply(salary_level)
employee_df

,name,age,city,salary,department,annual_salary,bonus,compensation,salary_level
0,Ram Sharma,25.0,Kathmandu,50000.0,Technology,600000.0,5000.0,55000.0,Low
1,Sita Thapa,28.0,Pokhara,65000.0,HR,780000.0,6500.0,71500.0,Medium
2,Hari Kc,NaN,Kathmandu,55000.0,Technology,660000.0,5500.0,60500.0,Medium
3,Gita Rai,30.0,Kathmandu,70000.0,Finance,840000.0,7000.0,77000.0,High
5,Nabin Gurung,27.0,Chitwan,60000.0,HR,720000.0,6000.0,66000.0,Medium

In [114]:
#lamda version
# employee_df=employee_df["salary"]=employee_df["salary"].apply(lambda x: "High" if x>=60000 else "Low")
# employee_df.head()

employee_df["salary_level"] = employee_df["salary"].apply(
    lambda x: "High" if x >= 60000 else "Low"
)

employee_df.head()

           name   age       city  salary department salary_level
0    Ram Sharma  25.0  Kathmandu   50000         IT          Low
1   sita Thapa   28.0    Pokhara   65000         HR         High
2       Hari KC   NaN  Kathmandu   55000         IT          Low
3      Gita Rai  30.0        NaN   70000    Finance         High
4    Ram sharma  25.0  Kathmandu   50000         IT          Low

In [129]:
#map()

department_code={
    "Technology":1,
    "HR":2,
    "Finance":3
}

employee_df["department_code"]=employee_df["department"].map(department_code)
employee_df.head()

,name,age,city,salary,department,salary_level,department_code
1,sita Thapa,28.0,Pokhara,65000,HR,High,2
3,Gita Rai,30.0,NaN,70000,Finance,High,3
5,Nabin Gurung,27.0,Chitwan,60000,HR,High,2

Filtering

In [115]:
employee_df[employee_df["salary"]>=55000]

           name   age       city  salary department salary_level
1   sita Thapa   28.0    Pokhara   65000         HR         High
2       Hari KC   NaN  Kathmandu   55000         IT          Low
3      Gita Rai  30.0        NaN   70000    Finance         High
5  Nabin Gurung  27.0    Chitwan   60000         HR         High

In [ ]:
employee_df[(employee_df["salary"]>=5000)]

In [86]:
employee_df[(employee_df["department"]=="HR") | 
            (employee_df["department"]=="Finance")]

employee_df.head()

           name   age       city salary department
0    Ram Sharma  25.0  Kathmandu  50000         IT
1   sita Thapa   28.0    Pokhara  65000         HR
2       Hari KC   NaN  Kathmandu  55000         IT
3      Gita Rai  30.0        NaN  70000    Finance
4    Ram sharma  25.0  Kathmandu  50000         IT

In [128]:
employee_df= employee_df[employee_df["department"].isin(["HR","Finance"])]
employee_df

           name   age     city  salary department salary_level
1   sita Thapa   28.0  Pokhara   65000         HR         High
3      Gita Rai  30.0      NaN   70000    Finance         High
5  Nabin Gurung  27.0  Chitwan   60000         HR         High

In [119]:
#sorting 
employee_df.sort_values("salary",ascending=False)
employee_df

           name   age       city  salary department salary_level
0    Ram Sharma  25.0  Kathmandu   50000         IT          Low
1   sita Thapa   28.0    Pokhara   65000         HR         High
2       Hari KC   NaN  Kathmandu   55000         IT          Low
3      Gita Rai  30.0        NaN   70000    Finance         High
4    Ram sharma  25.0  Kathmandu   50000         IT          Low
5  Nabin Gurung  27.0    Chitwan   60000         HR         High

In [126]:
employee_df.sort_values(["department","salary"],ascending=[True,False])

           name   age       city  salary department salary_level
3      Gita Rai  30.0        NaN   70000    Finance         High
1   sita Thapa   28.0    Pokhara   65000         HR         High
5  Nabin Gurung  27.0    Chitwan   60000         HR         High
2       Hari KC   NaN  Kathmandu   55000         IT          Low
0    Ram Sharma  25.0  Kathmandu   50000         IT          Low
4    Ram sharma  25.0  Kathmandu   50000         IT          Low

In [89]:
#Value count
employee_df["department"].value_counts()

department
IT         3
HR         2
Finance    1
Name: count, dtype: int64

In [90]:
employee_df["department"].value_counts(normalize=True)

department
IT         0.500000
HR         0.333333
Finance    0.166667
Name: proportion, dtype: float64

In [91]:
#unique and nunique
employee_df["department"].unique()

<StringArray>
['IT', 'HR', 'Finance']
Length: 3, dtype: str

In [94]:
employee_df["department"].nunique()

3

#groupby()
split-> apply->combine

In [123]:
#avergae salary of each department

employee_df.groupby("department")["salary"].mean()

department
Finance    70000.000000
HR         62500.000000
IT         51666.666667
Name: salary, dtype: float64

In [96]:
employee_df.groupby("department")["salary"].max()

department
Finance    70000
HR         65000
IT         55000
Name: salary, dtype: str

In [97]:
employee_df.groupby("department")["salary"].count()

department
Finance    1
HR         2
IT         3
Name: salary, dtype: int64

In [124]:
employee_df.groupby("department")["salary"].agg([
        "max",
        "mean",
        "min",
        "count"
      ]
    )

              max          mean    min  count
department
Finance     70000  70000.000000  70000      1
HR          65000  62500.000000  60000      2
IT          55000  51666.666667  50000      3

In [125]:
employee_df.groupby("department").agg({
    "salary":["mean","max"],
    "age":["mean","min"]
})

                  salary          age
                    mean    max  mean   min
department
Finance     70000.000000  70000  30.0  30.0
HR          62500.000000  65000  27.5  27.0
IT          51666.666667  55000  25.0  25.0

In [104]:
employee_df.columns

Index(['name', 'age', 'city', 'salary', 'department'], dtype='str')

In [107]:
employee_df["salary"].dtypes

In [108]:
employee_df.dtypes

name              str
age           float64
city              str
salary            str
department        str
dtype: object

In [111]:
employee_df["salary"].astype("float")

0    50000.0
1    65000.0
2    55000.0
3    70000.0
4    50000.0
5    60000.0
Name: salary, dtype: float64