In [2]:

import numpy as np
import pandas as pd

data = {
    "name": [
        "   Ram", "Sita", "Hari", "Gita",
        "NaBin", "ANita", "Bikash", "    Sunita"
    ],
    "department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "HR"
    ],
    "age": [25, 28, 32, 30, 26, 35, 29, 31],
    "salary": [
        50000, 65000, 75000, 70000,
        55000, 80000, 68000, 62000
    ]
}

employees = pd.DataFrame(data)
employees.head()

     name department  age  salary
0     Ram         IT   25   50000
1    Sita         HR   28   65000
2    Hari         IT   32   75000
3    Gita    Finance   30   70000
4   NaBin         HR   26   55000

- Display employees earning more than 60,000.
- Find employees from the IT department.
- Find IT employees earning more than 60,000.
- Sort employees by salary from highest to lowest.
- Find the average salary.
- Find average salary by department.
- Find maximum salary by department.
- Count employees in each department.
- Create an annual_salary column.
- Create a salary category:
```python
< 60,000       → Low
60,000–70,000 → Medium
> 70,000       → High
```
- Find the department with the highest average salary.
- Find the top 3 highest-paid employees.

In [16]:
employees["name"] = employees["name"].str.strip().str.title()
employees

     name department  age  salary  annual_salary salary_category
0     Ram         IT   25   50000         600000             Low
1    Sita         HR   28   65000         780000          Medium
2    Hari         IT   32   75000         900000            High
3    Gita    Finance   30   70000         840000          Medium
4   Nabin         HR   26   55000         660000             Low
5   Anita    Finance   35   80000         960000            High
6  Bikash         IT   29   68000         816000          Medium
7  Sunita         HR   31   62000         744000          Medium

In [ ]:

employees[employees["salary"] > 60000]
employees

     name department  age  salary  annual_salary salary_category
0     Ram         IT   25   50000         600000             Low
1    Sita         HR   28   65000         780000          Medium
2    Hari         IT   32   75000         900000            High
3    Gita    Finance   30   70000         840000          Medium
4   Nabin         HR   26   55000         660000             Low
5   Anita    Finance   35   80000         960000            High
6  Bikash         IT   29   68000         816000          Medium
7  Sunita         HR   31   62000         744000          Medium

In [29]:

employees[employees["department"] =="IT"]

     name department  age  salary
0     Ram         IT   25   50000
2    Hari         IT   32   75000
6  Bikash         IT   29   68000

In [ ]:

employees[(employees["department"]=="IT")& (employees["salary"]>60000)]

     name department  age  salary
2    Hari         IT   32   75000
6  Bikash         IT   29   68000

In [35]:
employees.sort_values("salary",ascending=False)

         name department  age  salary
5       ANita    Finance   35   80000
2        Hari         IT   32   75000
3        Gita    Finance   30   70000
6      Bikash         IT   29   68000
1        Sita         HR   28   65000
7      Sunita         HR   31   62000
4       NaBin         HR   26   55000
0         Ram         IT   25   50000

In [39]:
print("The average salary is:",employees["salary"].mean())

The average salary is: 65625.0

In [44]:
employees.groupby("department")["salary"].mean()

department
Finance    75000.000000
HR         60666.666667
IT         64333.333333
Name: salary, dtype: float64

In [45]:
employees.groupby("department")["salary"].max()

department
Finance    80000
HR         65000
IT         75000
Name: salary, dtype: int64

In [49]:
employees.groupby("department")["name"].count()

department
Finance    2
HR         3
IT         3
Name: name, dtype: int64

In [4]:
employees["department"].value_counts()

department
IT         3
HR         3
Finance    2
Name: count, dtype: int64

In [5]:
employees["annual_salary"] = employees["salary"] * 12

In [6]:
employees

         name department  age  salary  annual_salary
0         Ram         IT   25   50000         600000
1        Sita         HR   28   65000         780000
2        Hari         IT   32   75000         900000
3        Gita    Finance   30   70000         840000
4       NaBin         HR   26   55000         660000
5       ANita    Finance   35   80000         960000
6      Bikash         IT   29   68000         816000
7      Sunita         HR   31   62000         744000

In [7]:
def salary_category(salary):
    if salary < 60000:
        return "Low"
    elif salary <= 70000:
        return "Medium"
    else:
        return "High"

In [9]:
employees["salary_category"] = employees["salary"].apply(salary_category)
employees

         name department  age  salary  annual_salary salary_category
0         Ram         IT   25   50000         600000             Low
1        Sita         HR   28   65000         780000          Medium
2        Hari         IT   32   75000         900000            High
3        Gita    Finance   30   70000         840000          Medium
4       NaBin         HR   26   55000         660000             Low
5       ANita    Finance   35   80000         960000            High
6      Bikash         IT   29   68000         816000          Medium
7      Sunita         HR   31   62000         744000          Medium

In [13]:
employees.groupby("department")["salary"].mean().idxmax()

'Finance'

In [14]:
employees.nlargest(3, "salary")

    name department  age  salary  annual_salary salary_category
5  ANita    Finance   35   80000         960000            High
2   Hari         IT   32   75000         900000            High
3   Gita    Finance   30   70000         840000          Medium