Load Dataset

In [1]:
import numpy as np
import pandas as pd 

employee_df=pd.read_csv(r"D:\MovedFolder\DataSciencePythonevening\DataScienceCourse\pandas\dataset\messy_employee_data.csv")
employee_df.head(5)

,employee_id,name,age,gender,city,department,salary,experience_years,joining_date,performance_rating,status,email
0,1,Gita Rai,21,Male,Biratnagar,Finance,56000,4.0,2022-07-29,4.0,On Leave,gita_rai@example.com
1,2,Hari Kc,39,Male,Bhaktapur,IT,39000,6.0,2023-04-22,3.5,Active,hari_kc@example.com
2,3,Sabina Rana,27,Female,Biratnagar,Operations,56000,14.0,2025-04-21,2.8,Active,sabina_rana@example.com
3,4,Anita Karki,43,Female,Bhaktapur,Finance,47000,6.0,2023-11-21,2.3,Inactive,anita_karki@example.com
4,5,Gita Rai,32,Female,Butwal,Finance,33000,14.0,2025-01-03,2.4,Inactive,gita_rai@example.com

In [69]:
employee_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         126 non-null    int64
 1   name                126 non-null    str
 2   age                 120 non-null    str
 3   gender              126 non-null    str
 4   city                114 non-null    str
 5   department          126 non-null    str
 6   salary              105 non-null    float64
 7   experience_years    122 non-null    float64
 8   joining_date        126 non-null    str
 9   performance_rating  116 non-null    float64
 10  status              126 non-null    str
 11  email               123 non-null    str
 12  annual_salary       105 non-null    float64
 13  salary_level        126 non-null    str
 14  experience_level    126 non-null    str
dtypes: float64(4), int64(1), str(10)
memory usage: 14.9 KB

In [70]:
employee_df["name"] = employee_df["name"].str.strip().str.title()

In [71]:
print(employee_df["name"].head())

0       Gita Rai
1        Hari Kc
2    Sabina Rana
3    Anita Karki
4       Gita Rai
Name: name, dtype: str

In [73]:
employee_df["gender"] = employee_df["gender"].replace({
    "F": "Female",
    "M": "Male"
})

In [74]:
print(employee_df["gender"].value_counts())

gender
Female    64
Male      56
Name: count, dtype: int64

1. Load the CSV file into a Pandas DataFrame and inspect the first and last few rows.
2. Check the shape, column names, data types, and general information using shape, columns, dtypes, info() and describe().
3. Find the number of missing values in every column.
4. Identify duplicate rows and duplicate employee_id values.
5. Remove appropriate duplicates.
6. Clean the name column by removing unnecessary spaces and making capitalization consistent.
7. Standardize the city column. For example, values such as kathmandu, Kathmandu, and KTM should represent the same city.
8. Standardize the department column. Handle inconsistent values such as lowercase departments or Information Tech.
9. Standardize the gender column so values such as M, Male, F, and Female follow one consistent format.
10. Clean the salary column. Remove commas, Rs., N/A, or other invalid values and convert salary into a numeric datatype.
11. Clean the age column and convert invalid values such as unknown into missing values.
12. Clean experience_years and ensure it is numeric.
13. Convert joining_date into a proper Pandas datetime column despite the different date formats.
14. Clean the performance_rating column and handle invalid values such as five.
15. Standardize the status column.
16. Clean and standardize email addresses.
17. Decide how missing values should be handled. Explain why you chose to drop or fill missing values for each relevant column.
18. Create a new column called annual_salary using monthly salary.
19. Create a salary_level column:
```python
< 50,000 → Low
50,000–80,000 → Medium
> 80,000 → High
```
20. Create an experience_level column such as Junior, Mid, and Senior based on years of experience.
21. Find the average, minimum, maximum, and median salary.
22. Find the average salary for each department.
23. Find the highest-paid employee in each department.
24. Count how many employees belong to each department.
25. Find the average performance rating by department.
26. Find the average salary by city.
27. Find the city with the highest average salary.
28. Find the top 10 highest-paid employees.
29. Find employees earning more than 80,000.
30. Find employees from the IT department earning more than 70,000.
31. Find employees with more than 5 years of experience and a performance rating above 4.0.
32. Sort employees by salary from highest to lowest.
33. Find how many employees are Active, Inactive, and On Leave.
34. Compare the average salaries of Male and Female employees.
35. Find which department has the highest average performance rating.
36. Determine how many employees joined in each year.
37. Find employees who joined most recently.
38. Save the final cleaned DataFrame as:
```cleaned_employee_data.csv```

### Final Challenge

After completing the analysis, write at least 5 insights based on the dataset.

For example, don't simply write:

```IT average salary = 75,000.```

Write an actual observation such as:

```The IT department has one of the highest average salaries, which may indicate that technical roles receive higher compensation compared with several other departments.```

2. Check the shape, column names, data types, and general information using shape, columns, dtypes, info() and describe().

In [43]:
employee_df.shape

(126, 12)

The dataset has 126 rows and 12 columns.

In [5]:
print(employee_df.columns)

Index(['employee_id', 'name', 'age', 'gender', 'city', 'department', 'salary',
       'experience_years', 'joining_date', 'performance_rating', 'status',
       'email'],
      dtype='str')

In [23]:
print(employee_df.columns.tolist())

['employee_id', 'name', 'age', 'gender', 'city', 'department', 'salary', 'experience_years', 'joining_date', 'performance_rating', 'status', 'email']

In [7]:
employee_df.dtypes

employee_id             int64
name                      str
age                       str
gender                    str
city                      str
department                str
salary                    str
experience_years      float64
joining_date              str
performance_rating        str
status                    str
email                     str
dtype: object

In [8]:
employee_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         126 non-null    int64
 1   name                126 non-null    str
 2   age                 120 non-null    str
 3   gender              126 non-null    str
 4   city                114 non-null    str
 5   department          126 non-null    str
 6   salary              121 non-null    str
 7   experience_years    122 non-null    float64
 8   joining_date        126 non-null    str
 9   performance_rating  119 non-null    str
 10  status              126 non-null    str
 11  email               123 non-null    str
dtypes: float64(1), int64(1), str(10)
memory usage: 11.9 KB

In [9]:
employee_df.describe()

       employee_id  experience_years
count   126.000000        122.000000
mean     59.849206          8.254098
std      34.728217          4.797660
min       1.000000          0.000000
25%      30.250000          4.000000
50%      59.500000          9.000000
75%      89.750000         13.000000
max     120.000000         15.000000

3. Find the number of missing values in every column.

In [11]:
employee_df.isnull().sum()

employee_id            0
name                   0
age                    6
gender                 0
city                  12
department             0
salary                 5
experience_years       4
joining_date           0
performance_rating     7
status                 0
email                  3
dtype: int64

4. Identify duplicate rows and duplicate employee_id values.

In [17]:
duplicated_rows=employee_df.duplicated()
print("The number of duplicated rows are:",duplicated_rows.sum())

The number of duplicated rows are: 6

In [21]:
duplicated_employeesid=employee_df["employee_id"].duplicated()
print("The number of duplicated employees id:",duplicated_employeesid.sum())

The number of duplicated employees id: 6

5. Remove appropriate duplicates.

In [22]:
employee_df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
121     True
122     True
123     True
124     True
125     True
Length: 126, dtype: bool

In [72]:
employee_df=employee_df.drop_duplicates(subset="employee_id")
employee_df.head(5)

,employee_id,name,age,gender,city,department,salary,experience_years,joining_date,performance_rating,status,email,annual_salary,salary_level,experience_level
0,1,Gita Rai,21,Male,Biratnagar,Finance,56000.0,4.0,2022-07-29,4.0,On Leave,gita_rai@example.com,672000.0,Medium,Mid
1,2,Hari Kc,39,Male,Bhaktapur,IT,39000.0,6.0,2023-04-22,3.5,Active,hari_kc@example.com,468000.0,Low,Senior
2,3,Sabina Rana,27,Female,Biratnagar,Operations,56000.0,14.0,2025-04-21,2.8,Active,sabina_rana@example.com,672000.0,Medium,Senior
3,4,Anita Karki,43,Female,Bhaktapur,Finance,47000.0,6.0,2023-11-21,2.3,Inactive,anita_karki@example.com,564000.0,Low,Senior
4,5,Gita Rai,32,Female,Butwal,Finance,33000.0,14.0,2025-01-03,2.4,Inactive,gita_rai@example.com,396000.0,Low,Senior

In [26]:
employee_df.duplicated().sum()

np.int64(0)

Clean the name column by removing unnecessary spaces and making capitalization consistent.

In [27]:
employee_df["name"].str.strip().str.title()
employee_df.head(5)

,employee_id,name,age,gender,city,department,salary,experience_years,joining_date,performance_rating,status,email
0,1,Gita Rai,21,Male,Biratnagar,Finance,56000,4.0,2022-07-29,4.0,On Leave,gita_rai@example.com
1,2,Hari Kc,39,Male,Bhaktapur,IT,39000,6.0,2023-04-22,3.5,Active,hari_kc@example.com
2,3,Sabina Rana,27,Female,Biratnagar,Operations,56000,14.0,2025-04-21,2.8,Active,sabina_rana@example.com
3,4,Anita Karki,43,Female,Bhaktapur,Finance,47000,6.0,2023-11-21,2.3,Inactive,anita_karki@example.com
4,5,Gita Rai,32,Female,Butwal,Finance,33000,14.0,2025-01-03,2.4,Inactive,gita_rai@example.com

7. Standardize the city column. For example, values such as kathmandu, Kathmandu, and KTM should represent the same city.

In [29]:
employee_df["city"].unique()

<StringArray>
['Biratnagar',  'Bhaktapur',     'Butwal',   'Lalitpur',          nan,
  'Kathmandu',    'Chitwan',     'butwal',    'Pokhara',   'lalitpur',
  'bhaktapur', 'biratnagar']
Length: 12, dtype: str

In [31]:
employee_df["city"]=employee_df["city"].str.strip().str.lower()
employee_df["city"].unique()

<StringArray>
['biratnagar',  'bhaktapur',     'butwal',   'lalitpur',          nan,
  'kathmandu',    'chitwan',    'pokhara']
Length: 8, dtype: str

In [32]:
employee_df["city"]=employee_df["city"].str.title()

In [33]:
employee_df["city"].unique()

<StringArray>
['Biratnagar',  'Bhaktapur',     'Butwal',   'Lalitpur',          nan,
  'Kathmandu',    'Chitwan',    'Pokhara']
Length: 8, dtype: str

8. Standardize the department column. Handle inconsistent values such as lowercase departments or Information Tech.

In [45]:
employee_df["department"].unique()

<StringArray>
[         'Finance',               'IT',       'Operations',
               'HR',            'Sales',            'sales',
        'Marketing',       'operations',        'marketing',
               'it', 'Information Tech']
Length: 11, dtype: str

In [47]:
employee_df["department"].str.strip().str.lower()

0         finance
1              it
2      operations
3         finance
4         finance
          ...
121            hr
122            it
123            hr
124            hr
125         sales
Name: department, Length: 126, dtype: str

In [48]:
employee_df["department"].str.title()

0         Finance
1              It
2      Operations
3         Finance
4         Finance
          ...
121            Hr
122            It
123            Hr
124            Hr
125         Sales
Name: department, Length: 126, dtype: str

9. Standardize the gender column so values such as M, Male, F, and Female follow one consistent format.

In [49]:
employee_df["gender"].unique()

<StringArray>
['Male', 'Female', 'F', 'M']
Length: 4, dtype: str

In [59]:
employee_df["gender"].str.strip().str.lower()

0        male
1        male
2      female
3      female
4      female
        ...
121      male
122      male
123    female
124      male
125         f
Name: gender, Length: 126, dtype: str

In [68]:
employee_df["gender"]=employee_df["gender"].replace("M","male")

In [65]:
employee_df["gender"]=employee_df["gender"].replace("F","female")

In [70]:
employee_df["gender"]=employee_df["gender"].str.title()

In [72]:
employee_df["gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

10. Clean the salary column. Remove commas, Rs., N/A, or other invalid values and convert salary into a numeric datatype.

In [78]:
print(employee_df["salary"].dtype)

str

In [82]:
employee_df["salary"]=employee_df["salary"].str.replace(",","")

In [83]:
print(employee_df["salary"].dtype)

str

In [85]:
employee_df["salary"]=employee_df["salary"].str.replace("Rs","")

In [87]:
employee_df["salary"]=employee_df["salary"].str.replace(".","")

In [88]:
employee_df["salary"]=employee_df["salary"].astype(float)

In [89]:
print(employee_df["salary"].dtype)

float64

In [92]:
employee_df["salary"].isnull().sum()

np.int64(5)

In [94]:
mean_salary=employee_df["salary"].mean()
mean_salary

np.float64(74884.29752066116)

In [95]:
employee_df["salary"]=employee_df["salary"].fillna(mean_salary)

In [96]:
employee_df["salary"].isnull().sum()

np.int64(0)

11. Clean the age column and convert invalid values such as unknown into missing values.

In [97]:
print(employee_df["age"].dtype)

str

In [99]:
employee_df["age"].isnull().sum()

np.int64(6)

In [102]:
employee_df["age"]=pd.to_numeric(employee_df["age"],errors="coerce")

In [103]:
print(employee_df["age"].dtype)

float64

In [104]:
average_age=employee_df["age"].mean()
average_age

np.float64(33.577586206896555)

In [105]:
employee_df["age"]=employee_df["age"].fillna(average_age)

In [106]:
employee_df["age"].isnull().sum()

np.int64(0)

12. Clean experience_years and ensure it is numeric.

In [108]:
print(employee_df["experience_years"].dtype)

float64

In [109]:
employee_df["experience_years"].isnull().sum()

np.int64(4)

In [110]:
avg_experienceage=employee_df["experience_years"].mean()
print(avg_experienceage)

8.254098360655737

In [111]:
employee_df["experience_years"]=employee_df["experience_years"].fillna(avg_experienceage)

In [112]:
employee_df["experience_years"].isnull().sum()

np.int64(0)

13. Convert joining_date into a proper Pandas datetime column despite the different date formats.

In [114]:
print(employee_df["joining_date"])

0        2022-07-29
1        2023-04-22
2        2025-04-21
3        2023-11-21
4        2025-01-03
           ...
121      2022-05-22
122    May 31, 2022
123      2025-01-11
124      2023-05-15
125      2023-07-12
Name: joining_date, Length: 126, dtype: str

In [116]:
employee_df["joining_date"]=employee_df["joining_date"].str.strip()

In [119]:
employee_df["joining_date"]=pd.to_datetime(employee_df["joining_date"],format="mixed",errors="coerce")

In [120]:
print(employee_df["joining_date"].dtype)

datetime64[us]

In [126]:
employee_df["joining_date"].isnull().sum()

np.int64(2)

In [127]:
employee_df["joining_date"]=employee_df["joining_date"].fillna(employee_df["joining_date"].mode()[0])

In [128]:
employee_df["joining_date"].isnull().sum()

np.int64(0)

14. Clean the performance_rating column and handle invalid values such as five.

In [ ]:
employee_df["performance_rating"].unique()

<StringArray>
[ '4.0',  '3.5',  '2.8',  '2.3',  '2.4',  '2.2',  '3.4',  '3.9',  '3.0',
  '4.7',  '2.7',  '3.3',  '4.2',  '2.5',  '2.1',    nan,  '4.8',  '2.6',
  '3.2',  '3.1',  '3.8',  '3.6', 'five',  '4.1',  '3.7',  '4.6',  '4.9',
  '5.0',  '4.5',  '2.9',  '4.4',  '4.3',  '2.0']
Length: 33, dtype: str

In [123]:
employee_df["performance_rating"]=employee_df["performance_rating"].replace("five","5.0")

In [125]:
employee_df["performance_rating"].isnull().sum()

np.int64(7)

In [131]:
print(employee_df["performance_rating"].dtype)

str

In [133]:
employee_df["performance_rating"]=employee_df["performance_rating"].astype(float)

In [134]:
avg_rating=(employee_df["performance_rating"].mean())
avg_rating

np.float64(3.5126050420168067)

In [143]:
employee_df["performance_rating"]=employee_df["performance_rating"].fillna(avg_rating).round(2)

In [136]:
employee_df["performance_rating"].isnull().sum()

np.int64(0)

In [144]:
employee_df["performance_rating"].unique()

array([4. , 3.5, 2.8, 2.3, 2.4, 2.2, 3.4, 3.9, 3. , 4.7, 2.7, 3.3, 4.2,
       2.5, 2.1, 4.8, 2.6, 3.2, 3.1, 3.8, 3.6, 5. , 4.1, 3.7, 4.6, 4.9,
       4.5, 2.9, 4.4, 4.3, 2. ])

15. Standardize the status column.

In [201]:
#employee_df["status"].unique()

print(employee_df["status"].unique())

<StringArray>
['On Leave', 'Active', 'Inactive', 'active', 'on leave', 'inactive']
Length: 6, dtype: str

In [216]:
employee_df["status"]=employee_df["status"].str.strip()

In [217]:
employee_df["status"]=employee_df["status"].str.lower()

In [218]:
employee_df["status"]=employee_df["status"].str.title()

In [219]:
employee_df["status"]

0      On Leave
1        Active
2        Active
3      Inactive
4      Inactive
         ...
121    On Leave
122    On Leave
123      Active
124    On Leave
125    Inactive
Name: status, Length: 126, dtype: string

In [212]:
print(employee_df["status"].dtype)

str

In [214]:
employee_df["status"]=employee_df["status"].astype("string")

In [215]:
print(employee_df["status"].dtype)

string

In [196]:
employee_df["status"]=employee_df["status"].str.strip

In [178]:
employee_df["status"]=employee_df["status"].str.lower

In [197]:
employee_df["status"]=employee_df["status"].str.title()

In [198]:
employee_df["status"].value_counts()

Series([], Name: count, dtype: int64)

In [199]:
employee_df["status"].head(5)

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: status, dtype: float64

In [220]:
print(employee_df["status"].unique())

<StringArray>
['On Leave', 'Active', 'Inactive']
Length: 3, dtype: string

16. Clean and standardize email addresses.

In [221]:
employee_df["email"].isnull().sum()

np.int64(3)

18. Create a new column called annual_salary using monthly salary.

In [9]:
employee_df["salary"]=pd.to_numeric(employee_df["salary"],errors="coerce")

In [10]:
employee_df["annual_salary"]=employee_df["salary"]*12

In [11]:
employee_df["annual_salary"].head()

0    672000.0
1    468000.0
2    672000.0
3    564000.0
4    396000.0
Name: annual_salary, dtype: float64

19. Create a salary_level column:
```python
< 50,000 → Low
50,000–80,000 → Medium
> 80,000 → High

In [12]:
def salary_level(salary):
    if salary<50000:
        return "Low"
    elif salary<=80000:
        return "Medium"
    else:
        return"High" 

employee_df["salary_level"]=employee_df["salary"].apply(salary_level)

In [14]:
print(employee_df[["salary", "salary_level"]])

       salary salary_level
0     56000.0       Medium
1     39000.0          Low
2     56000.0       Medium
3     47000.0          Low
4     33000.0          Low
..        ...          ...
121       NaN         High
122   86000.0         High
123   70000.0       Medium
124   63000.0       Medium
125  117000.0         High

[126 rows x 2 columns]

20. Create an experience_level column such as Junior, Mid, and Senior based on years of experience.

In [16]:
def experience_level(experience_years):
    if experience_years<=2:
        return "Junior"
    elif experience_years<=5:
        return "Mid"
    else:
        return "Senior"

employee_df["experience_level"]=employee_df["experience_years"].apply(experience_level)

21. Find the average, minimum, maximum, and median salary.

In [19]:
print("The average salary of the employee is",employee_df["salary"].mean())

The average salary of the employee is 75285.71428571429

In [20]:
print("The minimum salary of the employee is",employee_df["salary"].min())

The minimum salary of the employee is 31000.0

In [21]:
print("The maximum salary of the employee is",employee_df["salary"].max())

The maximum salary of the employee is 118000.0

In [22]:
print("The maedian salary of the employee is",employee_df["salary"].median())

The maedian salary of the employee is 73000.0

22. Find the average salary for each department.

In [23]:
avg_salary=employee_df.groupby("department")["salary"].mean()
print(avg_salary)

department
Finance             71466.666667
HR                  76368.421053
IT                  58933.333333
Information Tech    69000.000000
Marketing           74428.571429
Operations          83812.500000
Sales               86117.647059
it                  80666.666667
marketing           43000.000000
operations          80000.000000
sales               72333.333333
Name: salary, dtype: float64

23. Find the highest-paid employee in each department.

In [28]:
high_emp=employee_df.loc[employee_df.groupby("department")["salary"].idxmax(),["name","department","salary"]]
print(high_emp)

               name        department    salary
46    Prakash Magar           Finance  118000.0
88      Rita Pandey                HR  118000.0
47      Bikash Lama                IT  107000.0
92     Suman Basnet  Information Tech   69000.0
94     Suman Basnet         Marketing  109000.0
99      Rita Pandey        Operations  118000.0
91   Pooja Shrestha             Sales  117000.0
83     Suman Basnet                it   89000.0
55     Kiran Khatri         marketing   43000.0
41      Mina Tamang        operations   80000.0
13    Prakash Magar             sales   98000.0

24. Count how many employees belong to each department.

In [31]:
emp_count=employee_df.groupby("department")["name"].count()
print(emp_count)

department
Finance             18
HR                  23
IT                  18
Information Tech     1
Marketing           15
Operations          20
Sales               23
it                   3
marketing            1
operations           1
sales                3
Name: name, dtype: int64

25. Find the average performance rating by department.

In [35]:
employee_df["performance_rating"]=pd.to_numeric(employee_df["performance_rating"],errors="coerce")

In [36]:
avg_performance=employee_df.groupby("department")["performance_rating"].mean()
print(avg_performance)

department
Finance             3.394444
HR                  3.371429
IT                  3.817647
Information Tech    2.300000
Marketing           3.750000
Operations          3.176471
Sales               3.547619
it                  3.066667
marketing           4.400000
operations          2.500000
sales               3.400000
Name: performance_rating, dtype: float64

26. Find the average salary by city.

In [37]:
avg_salcity=employee_df.groupby("city")["salary"].mean()
print(avg_salcity)

city
Bhaktapur      76750.000000
Biratnagar     55214.285714
Butwal         79000.000000
Chitwan        82166.666667
Kathmandu      87100.000000
Lalitpur       79400.000000
Pokhara        79769.230769
bhaktapur      72500.000000
biratnagar     70000.000000
butwal        108000.000000
lalitpur       65500.000000
Name: salary, dtype: float64

27. Find the city with the highest average salary.

In [40]:
#avg_salcity.mean()
city_avg=employee_df.groupby("city")["salary"].mean().sort_values(ascending=False)
print(city_avg)

city
butwal        108000.000000
Kathmandu      87100.000000
Chitwan        82166.666667
Pokhara        79769.230769
Lalitpur       79400.000000
Butwal         79000.000000
Bhaktapur      76750.000000
bhaktapur      72500.000000
biratnagar     70000.000000
lalitpur       65500.000000
Biratnagar     55214.285714
Name: salary, dtype: float64

28. Find the top 10 highest-paid employees.

In [44]:
emp_high=employee_df.groupby("name")["salary"].max().sort_values(ascending=False)
print(emp_high.head(10))

name
Rita Pandey          118000.0
Prakash Magar        118000.0
Anita Karki          117000.0
Pooja Shrestha       117000.0
  Sunita Bhandari    116000.0
RAM SHARMA           116000.0
  Pooja Shrestha     113000.0
RITA PANDEY          112000.0
Aayush Gautam        110000.0
Suman Basnet         109000.0
Name: salary, dtype: float64

29. Find employees earning more than 80,000.

In [57]:
high_earners=employee_df[employee_df["salary"]>80000]
print(high_earners)

     employee_id               name  age  gender        city  department  \
5              6            Hari Kc   38  Female    Lalitpur  Operations
7              8        Anita Karki   32  Female    Lalitpur          HR
10            11    Aayush Gautam     27  Female  Biratnagar       Sales
11            12        Sabina Rana   38  Female    Lalitpur  Operations
13            14      Prakash Magar   33  Female     Chitwan       sales
15            16    Ramesh Adhikari   37    Male      butwal          HR
16            17       nabin gurung   32    Male      Butwal          HR
19            20        Bikash Lama   43  Female         NaN       Sales
20            21      Aayush Gautam   21    Male     Chitwan   Marketing
27            28    Ramesh Adhikari   46  Female      Butwal       sales
30            31      Prakash Magar   24    Male     Chitwan          HR
32            33   Pooja Shrestha     35    Male    Lalitpur          IT
34            35     Pooja Shrestha   40    Male      Butwal  Operations
38            39         RAM SHARMA   24    Male   Kathmandu  Operations
46            47      Prakash Magar   39    Male     Pokhara     Finance
47            48        Bikash Lama   32  Female   bhaktapur          IT
49            50        Bikash Lama   34    Male         NaN       Sales
50            51     pooja shrestha   30  Female     Pokhara       Sales
51            52        RITA PANDEY   46    Male      Butwal  Operations
56            57       Kiran Khatri  NaN  Female     Chitwan     Finance
57            58        Rita Pandey   35  Female    Lalitpur          HR
60            61        Mina Tamang   22  Female     Pokhara       Sales
61            62        Sneha Joshi   30  Female      Butwal       Sales
64            65         SITA THAPA   29    Male   Bhaktapur     Finance
67            68       nabin gurung   28    Male     Pokhara       Sales
72            73       Nabin Gurung   34  Female     Pokhara  Operations
74            75     Nisha Maharjan   42    Male   Bhaktapur     Finance
75            76    Ramesh Adhikari  NaN  Female    Lalitpur   Marketing
76            77    Sunita Bhandari   44    Male   Bhaktapur       Sales
77            78         RAM SHARMA   23  Female    Lalitpur          HR
78            79        Rita Pandey   38  Female     Chitwan     Finance
83            84       Suman Basnet   31  Female     Pokhara          it
85            86        Sabina Rana   45    Male   Bhaktapur   Marketing
86            87      Dipesh Poudel   34    Male    Lalitpur   Marketing
88            89        Rita Pandey   30  Female   Kathmandu          HR
91            92     Pooja Shrestha   35       F   Kathmandu       Sales
93            94      Dipesh Poudel   39  Female   Kathmandu  Operations
94            95       Suman Basnet  NaN  Female     Pokhara   Marketing
96            97      Prakash Magar   47    Male      Butwal   Marketing
99           100        Rita Pandey   24    Male         NaN  Operations
101          102       kiran khatri   43  Female    Lalitpur       Sales
103          104    RAMESH ADHIKARI   47  Female   Kathmandu     Finance
104          105        Sneha Joshi   31  Female     Chitwan   Marketing
106          107      Prakash Magar   42    Male      Butwal  Operations
108          109       Nabin Gurung   23  Female   Bhaktapur     Finance
113          114    Sunita Bhandari  NaN    Male     Chitwan          HR
118          119    Ramesh Adhikari   42    Male      Butwal  Operations
122           33   Pooja Shrestha     35    Male    Lalitpur          IT
125           92     Pooja Shrestha   35       F   Kathmandu       Sales

       salary  experience_years  joining_date  performance_rating    status  \
5    101000.0               6.0    2025-12-13                 2.2  On Leave
7    117000.0               2.0    2025-06-01                 3.9  On Leave
10   110000.0              14.0    2022-10-20                 2.8    Active
11   102000.0              12.0    12/01/2024                 2.7    Active
13    98000.0               0.0    2025-10-25                 4.2  On Leave
15   108000.0               9.0    2025-08-01                 3.5    Active
16   104000.0              10.0    2024-09-27                 2.1  Inactive
19    84000.0              14.0    2022-09-05                 2.7    Active
20   103000.0               7.0    2022-01-15                 2.2  On Leave
27    82000.0              15.0    2022-11-14                 2.6    Active
30   107000.0               2.0    2024-05-08                 4.0  On Leave
32    86000.0               3.0  May 31, 2022                 3.6  On Leave
34   113000.0               9.0    2025-09-20                 NaN    Active
38    97000.0               1.0    2024-01-27                 3.7    Active
46   118000.0              13.0  invalid-date                 3.6  On Leave
47   107000.0              10.0    20/09/2025                 4.5  On Leave
49   106000.0               9.0    2024-04-11                 3.6    Active
50    87000.0              14.0    2024-06-24                 4.0  On Leave
51   112000.0               2.0    2023-08-05                 3.5  on leave
56   106000.0              13.0    2025-01-27                 3.3    Active
57    94000.0              15.0    2025-07-07                 2.7  Inactive
60   102000.0               0.0    2025-03-25                 3.1    Active
61    96000.0               7.0    2024-09-26                 2.7  Inactive
64    86000.0              10.0    2023-11-23                 4.3  Inactive
67   100000.0               6.0    2024-08-10                 4.1  Inactive
72   106000.0              15.0    2024-08-10                 3.3  On Leave
74    91000.0              10.0    2023-01-08                 3.5  Inactive
75    99000.0               0.0    2024-11-24                 4.8    Active
76   116000.0              15.0    2025-08-15                 4.1  Inactive
77   116000.0               7.0    2023-09-20                 4.0  inactive
78    98000.0              10.0    2023-12-22                 4.1  Inactive
83    89000.0               3.0    14/05/2022                 3.2    Active
85    94000.0              12.0    2024-07-11                 4.7  Inactive
86   106000.0               3.0    2023-03-02                 3.9  Inactive
88   118000.0               9.0    2025-12-10                 4.6    Active
91   117000.0              12.0    2023-07-12                 3.5  Inactive
93   101000.0               1.0  invalid-date                 3.4  On Leave
94   109000.0              15.0    2022-07-06                 3.4  Inactive
96    86000.0               2.0    2023-10-07                 2.8    Active
99   118000.0               5.0    2023-09-29                 3.7  On Leave
101   88000.0               7.0    2024-07-24                 3.7  Inactive
103  103000.0              15.0    2022-11-01                 3.3  inactive
104   86000.0              10.0    2023-01-22                 NaN    Active
106   91000.0               1.0    2022-09-16                 3.5  On Leave
108  107000.0              12.0    2025-08-23                 2.2  Inactive
113   87000.0               8.0    2024-07-30                 2.8    Active
118  108000.0               3.0    2025-07-09                 3.9  Inactive
122   86000.0               3.0  May 31, 2022                 3.6  On Leave
125  117000.0              12.0    2023-07-12                 3.5  Inactive

                           email  annual_salary salary_level experience_level
5            hari_kc@example.com      1212000.0         High           Senior
7        anita_karki@example.com      1404000.0         High           Junior
10     aayush_gautam@example.com      1320000.0         High           Senior
11       sabina_rana@example.com      1224000.0         High           Senior
13     prakash_magar@example.com      1176000.0         High           Junior
15   ramesh_adhikari@example.com      1296000.0         High           Senior
16      nabin_gurung@example.com      1248000.0         High           Senior
19       bikash_lama@example.com      1008000.0         High           Senior
20     AAYUSH_GAUTAM@EXAMPLE.COM      1236000.0         High           Senior
27   ramesh_adhikari@example.com       984000.0         High           Senior
30     prakash_magar@example.com      1284000.0         High           Junior
32    pooja_shrestha@example.com      1032000.0         High              Mid
34    pooja_shrestha@example.com      1356000.0         High           Senior
38        ram_sharma@example.com      1164000.0         High           Junior
46     prakash_magar@example.com      1416000.0         High           Senior
47       bikash_lama@example.com      1284000.0         High           Senior
49       bikash_lama@example.com      1272000.0         High           Senior
50    pooja_shrestha@example.com      1044000.0         High           Senior
51       rita_pandey@example.com      1344000.0         High           Junior
56      kiran_khatri@example.com      1272000.0         High           Senior
57       rita_pandey@example.com      1128000.0         High           Senior
60       mina_tamang@example.com      1224000.0         High           Junior
61       sneha_joshi@example.com      1152000.0         High           Senior
64        sita_thapa@example.com      1032000.0         High           Senior
67                           NaN      1200000.0         High           Senior
72      nabin_gurung@example.com      1272000.0         High           Senior
74    nisha_maharjan@example.com      1092000.0         High           Senior
75   ramesh_adhikari@example.com      1188000.0         High           Junior
76   sunita_bhandari@example.com      1392000.0         High           Senior
77        ram_sharma@example.com      1392000.0         High           Senior
78       rita_pandey@example.com      1176000.0         High           Senior
83      SUMAN_BASNET@EXAMPLE.COM      1068000.0         High              Mid
85       sabina_rana@example.com      1128000.0         High           Senior
86     dipesh_poudel@example.com      1272000.0         High              Mid
88       rita_pandey@example.com      1416000.0         High           Senior
91    pooja_shrestha@example.com      1404000.0         High           Senior
93     dipesh_poudel@example.com      1212000.0         High           Junior
94      suman_basnet@example.com      1308000.0         High           Senior
96     prakash_magar@example.com      1032000.0         High           Junior
99       rita_pandey@example.com      1416000.0         High              Mid
101                          NaN      1056000.0         High           Senior
103  ramesh_adhikari@example.com      1236000.0         High           Senior
104      SNEHA_JOSHI@EXAMPLE.COM      1032000.0         High           Senior
106    prakash_magar@example.com      1092000.0         High           Junior
108     nabin_gurung@example.com      1284000.0         High           Senior
113  sunita_bhandari@example.com      1044000.0         High           Senior
118  ramesh_adhikari@example.com      1296000.0         High              Mid
122   pooja_shrestha@example.com      1032000.0         High              Mid
125   pooja_shrestha@example.com      1404000.0         High           Senior

30. Find employees from the IT department earning more than 70,000.

In [51]:
it_high_earners=employee_df[(employee_df["department"]=="IT")&(employee_df["salary"]>70000)]
print(it_high_earners)

     employee_id              name age  gender       city department  \
32            33  Pooja Shrestha    35    Male   Lalitpur         IT
33            34   ramesh adhikari  25    Male   Lalitpur         IT
47            48       Bikash Lama  32  Female  bhaktapur         IT
122           33  Pooja Shrestha    35    Male   Lalitpur         IT

       salary  experience_years  joining_date  performance_rating    status  \
32    86000.0               3.0  May 31, 2022                 3.6  On Leave
33    75000.0               9.0    2022-11-20                 3.3  On Leave
47   107000.0              10.0    20/09/2025                 4.5  On Leave
122   86000.0               3.0  May 31, 2022                 3.6  On Leave

                          email  annual_salary salary_level experience_level
32   pooja_shrestha@example.com      1032000.0         High              Mid
33                          NaN       900000.0       Medium           Senior
47      bikash_lama@example.com      1284000.0         High           Senior
122  pooja_shrestha@example.com      1032000.0         High              Mid

In [50]:
print("Number of IT employees earning more than 70,000:", len(it_high_earners))

Number of IT employees earning more than 70,000: 4

In [55]:
print(it_high_earners.shape)

(4, 15)

31. Find employees with more than 5 years of experience and a performance rating above 4.0.

In [ ]:
employee_df["performance_rating"]=pd.to_numeric(employee_df["performance_rating"],errors="coerce")

In [59]:
experience_high_emp=employee_df[(employee_df["experience_years"]>5)&(employee_df["performance_rating"]>4.0)]
print(experience_high_emp)

     employee_id               name      age  gender        city department  \
18            19       Nabin Gurung      NaN    Male  Biratnagar      Sales
37            38         Sita Thapa      NaN  Female    Lalitpur         HR
43            44  Sunita Bhandari         21  Female  Biratnagar         HR
45            46         Sita Thapa       24       F     Chitwan      Sales
47            48        Bikash Lama       32  Female   bhaktapur         IT
55            56       Kiran Khatri       35    Male   Kathmandu  marketing
63            64        Sabina Rana       21    Male   bhaktapur  Marketing
64            65         SITA THAPA       29    Male   Bhaktapur    Finance
65            66  Ramesh Adhikari         45  Female      Butwal      Sales
66            67        Sneha Joshi       28    Male  Biratnagar         IT
67            68       nabin gurung       28    Male     Pokhara      Sales
73            74      Dipesh Poudel  unknown    Male    Lalitpur         HR
76            77    Sunita Bhandari       44    Male   Bhaktapur      Sales
78            79        Rita Pandey       38  Female     Chitwan    Finance
84            85      dipesh poudel       41    Male  Biratnagar         IT
85            86        Sabina Rana       45    Male   Bhaktapur  Marketing
88            89        Rita Pandey       30  Female   Kathmandu         HR
90            91    Ramesh Adhikari       47    Male     Pokhara         IT
105          106      Dipesh Poudel       33    Male     Pokhara      Sales
114          115       Suman Basnet       30       M  Biratnagar  Marketing
119          120       Suman Basnet       22    Male         NaN    Finance
124           74      Dipesh Poudel  unknown    Male    Lalitpur         HR

       salary  experience_years  joining_date  performance_rating    status  \
18    61000.0              13.0    2023-03-10                 4.8  On Leave
37    48000.0              14.0    2025-02-03                 4.1  On Leave
43        NaN               8.0    2022-05-23                 4.9  Inactive
45    68000.0              13.0    2025-05-26                 5.0    Active
47   107000.0              10.0    20/09/2025                 4.5  On Leave
55    43000.0              14.0    2022-10-01                 4.4  On Leave
63    38000.0              13.0    2022-10-05                 4.6    Active
64    86000.0              10.0    2023-11-23                 4.3  Inactive
65        NaN              15.0  Feb 09, 2022                 4.2    Active
66    31000.0               7.0    2023-02-13                 4.5  On Leave
67   100000.0               6.0    2024-08-10                 4.1  Inactive
73    63000.0              14.0    2023-05-15                 4.3  On Leave
76   116000.0              15.0    2025-08-15                 4.1  Inactive
78    98000.0              10.0    2023-12-22                 4.1  Inactive
84    47000.0               9.0    2022-06-24                 5.0    Active
85    94000.0              12.0    2024-07-11                 4.7  Inactive
88   118000.0               9.0    2025-12-10                 4.6    Active
90    49000.0               9.0    2025-05-03                 4.2  On Leave
105   68000.0              15.0    2025-12-15                 4.7  Inactive
114   37000.0              14.0    2023-12-09                 5.0  Inactive
119   39000.0               9.0    01/11/2023                 4.2    Active
124   63000.0              14.0    2023-05-15                 4.3  On Leave

                           email  annual_salary salary_level experience_level
18      nabin_gurung@example.com       732000.0       Medium           Senior
37        sita_thapa@example.com       576000.0          Low           Senior
43   sunita_bhandari@example.com            NaN         High           Senior
45        sita_thapa@example.com       816000.0       Medium           Senior
47       bikash_lama@example.com      1284000.0         High           Senior
55      kiran_khatri@example.com       516000.0          Low           Senior
63       sabina_rana@example.com       456000.0          Low           Senior
64        sita_thapa@example.com      1032000.0         High           Senior
65   ramesh_adhikari@example.com            NaN         High           Senior
66       sneha_joshi@example.com       372000.0          Low           Senior
67                           NaN      1200000.0         High           Senior
73     dipesh_poudel@example.com       756000.0       Medium           Senior
76   sunita_bhandari@example.com      1392000.0         High           Senior
78       rita_pandey@example.com      1176000.0         High           Senior
84     dipesh_poudel@example.com       564000.0          Low           Senior
85       sabina_rana@example.com      1128000.0         High           Senior
88       rita_pandey@example.com      1416000.0         High           Senior
90   ramesh_adhikari@example.com       588000.0          Low           Senior
105    dipesh_poudel@example.com       816000.0       Medium           Senior
114     suman_basnet@example.com       444000.0          Low           Senior
119     suman_basnet@example.com       468000.0          Low           Senior
124    dipesh_poudel@example.com       756000.0       Medium           Senior

In [60]:
experience_high_emp.shape

(22, 15)

32. Sort employees by salary from highest to lowest.

In [64]:
print(employee_df.sort_values("salary",ascending=False))

     employee_id            name age  gender       city  department    salary  \
46            47   Prakash Magar  39    Male    Pokhara     Finance  118000.0
88            89     Rita Pandey  30  Female  Kathmandu          HR  118000.0
99           100     Rita Pandey  24    Male        NaN  Operations  118000.0
7              8     Anita Karki  32  Female   Lalitpur          HR  117000.0
125           92  Pooja Shrestha  35       F  Kathmandu       Sales  117000.0
..           ...             ...  ..     ...        ...         ...       ...
98            99   Rita Pandey    41    Male  Bhaktapur          IT       NaN
107          108   Aayush Gautam  48    Male  Kathmandu       Sales       NaN
109          110   Sabina Rana    33  Female        NaN  Operations       NaN
116          117   DIPESH POUDEL  32  Female    Chitwan     Finance       NaN
121           18  Pooja Shrestha  28    Male  Kathmandu          HR       NaN

     experience_years  joining_date  performance_rating    status  \
46               13.0  invalid-date                 3.6  On Leave
88                9.0    2025-12-10                 4.6    Active
99                5.0    2023-09-29                 3.7  On Leave
7                 2.0    2025-06-01                 3.9  On Leave
125              12.0    2023-07-12                 3.5  Inactive
..                ...           ...                 ...       ...
98                4.0  Aug 13, 2023                 3.3  On Leave
107               NaN    01/02/2022                 NaN  Inactive
109               1.0    2025-06-18                 2.2  On Leave
116              12.0    2023-07-17                 2.0  On Leave
121              15.0    2022-05-22                 NaN  On Leave

                          email  annual_salary salary_level experience_level
46    prakash_magar@example.com      1416000.0         High           Senior
88      rita_pandey@example.com      1416000.0         High           Senior
99      rita_pandey@example.com      1416000.0         High              Mid
7       anita_karki@example.com      1404000.0         High           Junior
125  pooja_shrestha@example.com      1404000.0         High           Senior
..                          ...            ...          ...              ...
98      rita_pandey@example.com            NaN         High              Mid
107   aayush_gautam@example.com            NaN         High           Senior
109     sabina_rana@example.com            NaN         High           Junior
116   dipesh_poudel@example.com            NaN         High           Senior
121  pooja_shrestha@example.com            NaN         High           Senior

[126 rows x 15 columns]

33. Find how many employees are Active, Inactive, and On Leave.

In [67]:
emp_status=employee_df["status"].value_counts()
print(emp_status)

status
On Leave    45
Inactive    39
Active      38
inactive     2
active       1
on leave     1
Name: count, dtype: int64

34. Compare the average salaries of Male and Female employees.

In [75]:
emp_compare=employee_df.groupby("gender")["salary"].mean()
print(emp_compare)

gender
Female    77980.769231
Male      72520.833333
Name: salary, dtype: float64

35. Find which department has the highest average performance rating.